apiVersion: v1
kind: Service
metadata:
    name: user-management-service
spec:
    ports:
        -
            port: 80
            targetPort: 8090
    selector:
        app: user-management-service
